### ISSUE TITLE
Where are you located? Poll

### ISSUE THREAD

**Issue by moimikey** [beerjs/nyc#10]
Hi all,

To resurrect our chapter from the dead, I wanted to get peoples "leave from" locations, from where you'll travel to our meetups. Therefore, if you live in Queens and travel to Manhattan for work, and you're most likely to leave from work to our meetup, then choose Manhattan as your choice.

**Comment by ghost** [comment]
Greenwich Village, Manhattan

**Comment by maniart** [comment]
Chelsea, Manhattan

**Comment by anyagk** [comment]
flatiron/kips bay, manhattan

**Comment by moimikey** [comment]
chelsea/flatiron

**Comment by alexburgos** [comment]
flatiron

**Comment by bradoyler** [comment]
Midtown, manhattan.

**Comment by brentmulligan** [comment]
Greenpoint, Brooklyn

**Comment by moimikey** [comment]
thank you so far to those who have replied. i'll leave this open for another few days and then i'll post our next event in a nice centralized location :)

**Comment by cheshireoctopus** [comment]
crown heights, bk

**Comment by jeremiak** [comment]
LES or Flatiron/Chelsea

**Comment by moimikey** [comment]
thanks so far all. i'll be creating the event very soon :) keep your eyes peeled

**Comment by moimikey** [comment]
closing. thanks everyone. event coming up after halloween!!!
