### ISSUE TITLE
React & Flux

### ISSUE THREAD

**Issue by moimikey** [beerjs/nyc#3]
I currently work at ShopKeep in downtown manhattan (across the street from Adafruit actually), and we recently had a long battled outcome of using React to re-develop our BackOffice (what ShopKeep customers use to administer their accounts). We're still deciding on what implementation of Flux to use, but so far we're strong proponents of using Marty.

**Comment by alexburgos** [comment]
@moimikey I actually wanted to try out Delorean http://deloreanjs.com/
Great name too!

**Comment by moimikey** [comment]
Love the name also :) i've been doing multiple passes at https://github.com/voronianski/flux-comparison

**Comment by ml242** [comment]
Hi Michael! So what did you pick? Do you think you would have done anything differently with the new crop of Flux Capacitors?

**Comment by moimikey** [comment]
@ml242 hi Matt :). Welp, a good almost year later, the front runner seems to be Redux. I have been starting to have interest in [Cycle.js](http://cycle.js.org) too.

**Comment by moimikey** [comment]
at ShopKeep however, we ended up using FluxThis—not my first choice—which I think some of the team had eventually regretted.

**Comment by ml242** [comment]
I'm also interested in seeing where Cycle goes. Ditching JSX for the simplified syntax seems like a real plus. You're still stuck with picking a flux-ish store library to track component states though I think. Never heard of FluxThis.... 

Even on small apps this can turn into a real drag.

**Comment by ml242** [comment]
btw, your portfolio site doesn't suck

heh heh heh heh heh heh heh

**Comment by moimikey** [comment]
ditching the JSX is all good. i agree. Interestingly, if you wanted to still use JSX, you can still do that with cycle. You can reuse the babel transform for jsx. I tried it and it worked perfectly. With cycle, it works similarly to redux. It can have a single source of truth and pass down props (but in cycle they're just called `attributes`). the single source of truth can just be one big immutable object.

why thank you :). i tried to make it colorful.

**Comment by moimikey** [comment]
this was also an interesting thread on the argument between up-down vs down-up state: https://github.com/cyclejs/cycle-core/issues/191
