### ISSUE TITLE
Come to our first beer session this Friday, May 8th!

### ISSUE THREAD

**Issue by moimikey** [beerjs/nyc#5]
HALLO! :beer: 

Apologies for such short notice, but don't despair, it's after work!

We'll be meeting this **Friday** at **Zum Schneider** (http://nyc.zumschneider.com/) at **6:30 PM - 8:30 PM** (18:30 - 20:30)

We're gonna try to get some outside tables, but if not, we'll be inside at the bar!

Hope to see some new and/or familiar faces!!!
![beermug](https://cloud.githubusercontent.com/assets/182661/7504101/8dd00dc2-f415-11e4-9ef2-276a9903668f.jpg)

```
Zum Schneider NYC
107 Ave C @ East 7th Street
New York, NY 10009, USA
info@zumschneider.com
(212) 598-1098
nyc.zumschneider.com
```

**Comment by jeremiak** [comment]
Sweet, see you there!

**Comment by moimikey** [comment]
Thanks to those that came! We all had a really spectacular time and we'll do it again next week!!
