### ISSUE TITLE
BeerJS NYC Meetup No. 2 // @ BlindTiger; Friday, May 29th 2015

### ISSUE THREAD

**Issue by moimikey** [beerjs/nyc#7]
Hi All,

We'll be meeting tonight at **BLIND TIGER** @ 6:30pm-8pm

![screen shot 2015-05-29 at 9 50 34 am](https://cloud.githubusercontent.com/assets/182661/7883915/31139218-05e8-11e5-9f97-5b8026f0208c.png)

**Comment by jeremiak** [comment]
+1 for Blind Tiger, looks like a killer beer list.

See you all on the 29th

**Comment by moimikey** [comment]
I'll give 1 vote for Blind Tiger, and 1 vote for Burp Castle.

**Comment by ionox0** [comment]
+1 for another meetupa anywhere

**Comment by moimikey** [comment]
yaaaassss!!

**Comment by alexburgos** [comment]
+1 Blind Tiger is a winner. Would like to check the other options in following meetups tho.

**Comment by alexburgos** [comment]
+1 for Burp Castle as well, those monks know what's up.

**Comment by moimikey** [comment]
added ticks for Blind Tiger. seems to be winning although we're sort of biased, lol.

**Comment by jdaudier** [comment]
bummer, I'll be at JSConf.... will try for the next one.

**Comment by moimikey** [comment]
aww no worries joanne! we'll have more!

**Comment by moimikey** [comment]
I just updated our bar details all! We're be going to BLIND TIGER tonight from 6:30 to 8pm!

**Comment by moimikey** [comment]
Anyone new that's coming, I'm wearing a forest green crew neck shirt with a pocket and a messenger bag with a black strap across. And we're sitting at a table by the window
