### ISSUE TITLE
BeerJS Meetup: Trois/3/III (RESCHEDULED/TBD)

### ISSUE THREAD

**Issue by moimikey** [beerjs/nyc#9]
TBD 2015 @ 6:30 PM — 8:30 PM
@ [Arts and Crafts Beer Parlor](http://www.yelp.com/biz/arts-and-crafts-beer-parlor-new-york)

**Laptops welcome** for showing open source work and/or personal projects. Bar has **free WiFi**.

**Comment by ionox0** [comment]
outstanding

**Comment by jeremiak** [comment]
Would it work for folks to have it on a day of the week _not_ a Friday? Like maybe Thursday or even Tuesday?

**Comment by ionox0** [comment]
could do^

**Comment by alexburgos** [comment]
SUNDAY

**Comment by alexburgos** [comment]
JK

**Comment by moimikey** [comment]
a Thursday would be fine if everyone agrees

**Comment by alexburgos** [comment]
I'm ok with a Thursday

**Comment by ionox0** [comment]
Yea I could do Thurs

**Comment by jeremiak** [comment]
After all that making yall move your schedules around, I'm actually going to be in Minneapolis that day :/

But I'll probably be having beer and talking about something related to JS, so it kind of counts

**Comment by moimikey** [comment]
@jeremiak it's not set in stone. i could make it the day before :P

**Comment by jeremiak** [comment]
There that day as well, and through the weekend :/ If yall wanna wait till the following week I'm in, otherwise no worries and I'll just be at the following one for sure

**Comment by jeremiak** [comment]
I think it's time for a farewell summer :beer:, what would ya'll say to getting together at [Arts and Crafts Beer Parlor](http://www.yelp.com/biz/arts-and-crafts-beer-parlor-new-york) next Wednesday (10/28) at 6 PM?

**Comment by moimikey** [comment]
yaaaasssss!

**Comment by jeremiak** [comment]
I fucked up and somehow thought this was tonight :/

Yes, yes, I know that I proposed the date and time. Sorry ya'll

**Comment by moimikey** [comment]
let's try again :)? we should get a head count.

**Comment by brentmulligan** [comment]
Hey, I am down to check out the next one.

**Comment by moimikey** [comment]
pretty sure we have a meetup.com page. if not, ill make one and link everyone here. but we should come up with a new date

/cc @ionox0 @alexburgos

**Comment by moimikey** [comment]
@brentmulligan great! stay tuned!

**Comment by alexburgos** [comment]
@moimikey sorry just seeing all of these, can't wait to see ya guys!
